GET http://localhost:7070/students

###

POST http://localhost:7070/students
Content-Type: application/x-www-form-urlencoded

name=Akmal&surname&Ortiqov&age&19&group=Ortioqvdev

###

POST http://localhost:7070/students
Content-Type: application/json

{
    "name": "Akmal",
    "surname": "Ortiqov",
    "age": 19,
    "group": "OrtiqovDev"
  }

###

DELETE http://localhost:7070/students/0